language: java
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  file: /home/travis/build/altayeb1980/Demo/target
  skip_cleanup: true
  on:
    branch: master
  