language: java
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  file: Demo-1.0.jar
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
  