language: java
jdk: oraclejdk8

install: true
script: mvn install


after_success:
- pwd
- mkdir $HOME/buildApk/
- ls -l
- cd $HOME/buildApk/
- pwd
- ls -l
- git config --global user.email "loay.saada@gmail.com"
- git config --global user.name "Altayeb Saadeh"
- git clone --depth=50 --branch=master https://github.com/altayeb1980/Demo.git
- cd Demo
- ls -l
- cp -r /home/travis/build/altayeb1980/Demo/target $HOME/buildApk/
- ls -l
- git add -f .
- git remote rm origin
- git remote add origin https://$GITHUB_TOKEN@github.com/altayeb1980/Demo.git
- git add -f .
- git commit -m "Travis Build $TRAVIS_BUILD_NUMBER pushed"
- git push -fq origin master
 